version: '3'

services:

  db:
    image: mysql:5.7.29
    container_name: chivo_cuate_db
    ports:
      - 3307:3306
    volumes:
      - ./docker-volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=Root123*
      - MYSQL_DATABASE=u715364900_chivocuate
      - MYSQL_USER=u715364900_chivocuate
      - MYSQL_PASSWORD=ChivoCuate123*
