name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Update dependencies
      run: composer update

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run test suite
      run: ./vendor/bin/codecept run

